apiVersion: networking.gloo.solo.io/v2
kind: VirtualGateway
metadata:
  name: cluster1-north-south-gw-443
  namespace: istio-gateways
spec:
  listeners:
  - http: {}
    port:
      number: 443
    tls:
      mode: SIMPLE
      secretName: tls-secret
    # specify a host
    #allowedRouteTables:
    #  - host: .....glootest.com
  workloads:
  - selector:  # Selects which Istio Ingress gateway(s) this is configuring
      cluster: cluster1
      labels:
        istio: ingressgateway
